/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BookController;
import Model.DTO.BookDTO;
import com.mysql.cj.x.protobuf.MysqlxDatatypes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author vutro
 */
public class JFBook extends javax.swing.JFrame {

    /**
     * Creates new form JFBook
     */
    BookController bc = BookController.GetInstance();

    public JFBook() {
        initComponents();

        getAllBook.addActionListener((ae) -> {

            int size = bc.getAllBook().size();
            JFrame jf = new JFrame();
            BookDTO row[] = new BookDTO[size];
            ArrayList<BookDTO> getallbook = bc.getAllBook();
//            for (int i = 0; i < size; i++) {
//                for (int j = 0; i < 8; i++) {
//                    row[i] = getallbook.get(i);
//                }
//            }
            Object colunm[] = new Object[]{"id", "name", "author", "producer", "type", "publishing_company", "issue_number", "price"};
            JTable jt = new JTable();
        
            DefaultTableModel model = new DefaultTableModel();
            jt.setModel(model);
            model.setColumnIdentifiers(colunm);
//            JTable jt = new JTable(new Object[][]{
////                {  row[1].getId(),row[1].getName(),row[1].getAuthor(),row[1].getProducer(),row[1].getType(),row[1].getPublishing_company(),row[1].getIssue_number(),row[1].getPrice(),}
//                {"323","2323","234","234","23423","234","32423","3242"}
//            },new Object[]{
//                "id","name","author","producer","type","publishing_company","issue_number","price"
//            });
////            jt.setModel(new DefaultTableModel();
//            jt.addColumn(new DefaultTableModel(new Object[]{
//                "id","name","author","producer","type","publishing_company","issue_number","price"
//            }));
            for (BookDTO bookDTO : getallbook) {
                String[] data = new String[8];
                data[0] = bookDTO.getId() + "";
                data[1] = bookDTO.getName();
                data[2] = bookDTO.getAuthor();
                data[3] = bookDTO.getProducer();
                data[4] = bookDTO.getType();
                data[5] = bookDTO.getPublishing_company();
                data[6] = String.valueOf(bookDTO.getIssue_number());
                data[7] = String.valueOf(bookDTO.getPrice());
                model.addRow(data);
            }
            

            JScrollPane sp = new JScrollPane();
            sp.setViewportView(jt);
            jf.add(sp);
            jf.pack();
            jf.setVisible(true);
//          jf.setDefaultCloseOperation(HIDE_ON_CLOSE);
        });
        //      Search
        Search.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
               String Name =  JOptionPane.showInputDialog("nhap ten sach can tìm kiếm");
               BookDTO book2 = new BookDTO();
                    book2 = bc.getBookByName(Name);
               if(book2 != null){
                   JOptionPane.showMessageDialog(null,book2.toString());
               }else{
                JOptionPane.showMessageDialog(rootPane,"ko co sach nay");
            }
            }
        });
        // Add
        Add.addActionListener((ae) -> {
            
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        getAllBook = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("       Book");

        getAllBook.setText("Get All Book");

        Search.setText("Search");

        Delete.setText("Delete");

        Update.setText("Update");

        Add.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(getAllBook)
                        .addGap(18, 18, 18)
                        .addComponent(Search)
                        .addGap(18, 18, 18)
                        .addComponent(Delete)
                        .addGap(18, 18, 18)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAllBook)
                    .addComponent(Search)
                    .addComponent(Delete)
                    .addComponent(Update)
                    .addComponent(Add))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JButton getAllBook;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
